### ISSUE TITLE
Pocket Hole Line not Recognized

### ISSUE THREAD

**Issue by Nanclus** [marvingreenberg/FaceSVG#13]
Hi Marvin,

Thanks for your help on the outside relief btw. 

So I was trying out my first file tonight, and I was making a simple pocket rectangle in a larger rectangle... I got the face and exported the SVG layout. When I brought it over to SO, the outside had the dancing ants no issues, but the pocket line... the SO never had the dancing ants like it was ready to cut? I did a 2nd try and removed the grey rectangle your software created thinking it was getting confused because when I did the relief cuts the rectangle didn't match the now relief cut shape. My plan was to just on SO set that to pocket on the fly.... but even if SO recognized that as an inside line still no dancing ants?

I tried with a different sketchup extension that it worked sorta, it did recognize the pocket line... but I like yours way better and I would really like to figure out what I did wrong.

I have attached my sketchup file, and a picture of the SO screen... any thoughts??? Thanks so much for your help.

Thanks again,
Jordan

[test example.skp.zip](https://github.com/marvingreenberg/FaceSVG/files/1840234/test.example.skp.zip)
![img_4746](https://user-images.githubusercontent.com/37671030/37812382-c13bd3e4-2e2d-11e8-8c8b-1baab70ddb4b.JPG)

**Comment by marvingreenberg** [comment]
It isn't clear what the dimensions are in your picture.  I had experienced similar issues when I had mistakenly set cut offset.  Try setting your bit diameter to something crazy small, like 0.1 and see if the interior cut line is recognized.

The plugin just creates SVG, no other magic.  In your picture, SO recognizes the line as an inside cut, but the tool is for some reason deciding it can't cut.  What are the dimensions of the slot?  I've similarly had the tool decide it can't cut 1 corner relief arc, but could cut the other three.  I've just set a small negative offset to get it to cut the errant corner, like -0.02

**Comment by marvingreenberg** [comment]
The problem is your geometry - it has nothing to do with the generated SVG or the pocket cut.  I looked at your model. and that slot is 0.25" wide, so trying to cut it with a 0.25" bit (as you have set) won't work, which is why SO is not enabling cut (and the corner reliefs could certainly never be cut.)  In situations where you really want to cut a mortise right at the bit size you can set a small negative offset.  But things like corner reliefs would make no sense.

**Comment by Nanclus** [comment]
Ah, thanks so much. I didn't think the SO would react that way. I just figured it would "overcut" the original geometry vs stop it all together. Thanks!!!!
