### ISSUE TITLE
interior shapes not visable in inkscape 

### ISSUE THREAD

**Issue by moray-msj** [marvingreenberg/FaceSVG#26]
so i am creating files to use my k40 laser cutter and while its displaying the outer edges in inkscape the inner edges are present but are only able to be solid colours not single line paths the software im using to control the laser is k40 whisperer which requires red paths for cutting hopefully you can advise 

thanks in advance 
moray
![example](https://user-images.githubusercontent.com/48754550/55843314-8f765c00-5b2f-11e9-9f0d-7ef54cd4334d.jpg)

 
[moray model error.zip](https://github.com/marvingreenberg/FaceSVG/files/3061438/moray.model.error.zip)

**Comment by marvingreenberg** [comment]
This is working exactly as designed.  I have done some initial work that would allow customizing the various settings like fill and line colors, but haven't really been working on this software much.

The FaceSVG software is not designed for the laser cutter you mention - it is designed for the Shaper Origin "CNC" router.  As a result, the cut paths are being generated as expected.  There is nothing to prevent you from changing the paths to be red or any other color, in Inkscape or just by editing the file directly.  I did that, changing the "stroke" to rgb(225,0,0) for all the "interior" paths.


[moray_model_edited.zip](https://github.com/marvingreenberg/FaceSVG/files/3063796/moray_model_edited.zip)
