### ISSUE TITLE
Completely Broken in SketchupPro 2024

### ISSUE THREAD

**Issue by TikiTD** [marvingreenberg/FaceSVG#46]
Any chance there will be another update to add compatibility with SketchUp Pro 2024?  This plugin was a lifesaver, but now I got nothin . . . :(

**Comment by BennM666** [comment]
In folder "/lib/facesvg/", edit files "bounds.rb" and "su_util.rb" to replace :
`Sketchup.require('matrix')`
by
`require('matrix') unless defined?(Matrix)`

I believe that Sketchup.require requires a full path, whereas this is not the case with require (ruby command).

**Comment by pengel2000** [comment]
That fixed it!!! Thanks!!! @marvingreenberg , if you ever need a beta tester, let me know. I'm a former .Net programmer, and am willing to help out if you need someone w/ SketchUp Pro to test something.

**Comment by AustinArch60** [comment]
@BennM666 ... I have SO 2024 and would like to use FaceSVG. However, I am a complete novice when it comes to the edits you have offered. Can you help explain to me how to get to the /lib/facesvg/ and make the changes?  I am on a MacBook Pro running the mac version of SU 2024 Pro. I am running OS Ventura 13.2.1. Any help will be appreciated

**Comment by pengel2000** [comment]
I’m away from my house right now. I’ll get back to you tomorrow & give you simple instructions. Cheers.

**Comment by AustinArch60** [comment]
Thanks. That would be great! Sincerely,Michael ***@***.***(512)294-4276On Aug 3, 2024, at 5:31 PM, pengel2000 ***@***.***> wrote:﻿
I’m away from my house right now. I’ll get back to you tomorrow & give you simple instructions. Cheers.

**Comment by pengel2000** [comment]
Michael,

I'm assuming you already have facesvg installed as a plugin. If not, there are instructions for that with the download.

I'm probably going to be too simplistic here...but I want to make sure I make this as clear as I can in case you are not as tech experienced as me. The only tricky part of this is to find your Library folder. To do that, open a finder window. (The icon is the blue and white face. Of, if you just click anywhere on your desktop, you will get the same menu that you need to access.) Once it's open, hold down the Option key on your keyboard, and while holding it, click on the "Go" item in your menu at the top of the screen. You will see "Library". Click that. It's always hidden if you just go hunting for it unless you are holding down the Option key while opening the Go menu.

At this point, you will want to make sure you are in List view. It should be the second icon from the left at the top of your finder window, and looks like a bullet list. Then sort by name by clicking the Name column header. On my computer, the 5th folder down is Application Support. Double-click that. Scroll down to the SketchUp 2024 folder. Double-click that. Then double-click the SketchUp folder. Now double-click the Plugins folder. Navigate down to the FaceSVG folder. Double-click to open it. You will see a file called svg_util.rb. Right-click it and select Open With/TextEdit.app.

Once you have it open, you will see a line that says "Sketchup.require('matrix')". You can just type a pound sign and space at the start of that line, and it will comment it out. So it will look like this...# Sketchup.require('matrix')

Now, paste the following line in right after the line you just commented out:
require('matrix') unless defined?(Matrix)

Save the file and close it. Now, when you open SketchUp, it should work. Hope this works out for you.

**Comment by Bazzarre** [comment]
The fix above is Mac specific. For PC navigate to...
(c:)/users/yourname/appdata/roaming/sketchup/sketchup24/sketchup/plugins/facesvg. Open su-util in notepad and replace...

Sketchup.require('matrix')  with  require('matrix') unless defined?(Matrix)

Cheers.

**Comment by marvingreenberg** [comment]
I uploaded the fix per @Bazzarre.  Or maybe I did it differently - but this seems to work now with the updated Ruby in Sketchup 2024.  This is release 3.1.0 now https://github.com/marvingreenberg/FaceSVG/releases.

Reopen or comment here  if you have issues.  I should get to it within another year or so :-o ;-)

**Comment by pengel2000** [comment]
👍

Regards,
Paul
Chief Termite
Acute Engel Wood Worx
________________________________
