### ISSUE TITLE
Unexpected exceptions for some faces selections

### ISSUE THREAD

**Issue by marvingreenberg** [marvingreenberg/FaceSVG#7]
Variously, the plugin will raise exceptions complaining about referencing a _deleted_ material.  Materials are used to mark faces as either Surface faces or Pocket faces.  The code creates specific materials for this purpose, and ensures they exist.  It is not clear what is causing the exception

**Comment by marvingreenberg** [comment]
Have not been seeing these exceptions.  Will leave this open, anyone experiencing this issue may comment.

**Comment by marvingreenberg** [comment]
Fixed in development branch, patched into 2.0.0 release rbz

**Comment by marvingreenberg** [comment]
merged up with 2.1.0 release

**Comment by ropandsaw** [comment]
Hey Marvin, I've been receiving the complaints in regards to deleted data from an object in Sketchup. More specifically I've been trying to create an .svg from a model from the 3D warehouse. It's a model for Systainer top and bottom inserts. The plugin doesn't seem to like the bottom insert (won't let me layout svg) and though I can layout an svg for the top insert, it ultimately won't let me write the file- complains about unexpected: no edge/d
![screen shot 2018-03-09 at 2 27 46 pm](https://user-images.githubusercontent.com/37227762/37231819-da2f9388-23a9-11e8-91a9-4f44f3478985.png)
arc connection...

![screen shot 2018-03-09 at 2 15 14 pm](https://user-images.githubusercontent.com/37227762/37231870-fcab00be-23a9-11e8-8149-c9939c4e131c.png)

**Comment by ropandsaw** [comment]
The model I've been playing with:
![screen shot 2018-03-09 at 2 57 08 pm](https://user-images.githubusercontent.com/37227762/37231928-3af301aa-23aa-11e8-8101-1c92b8a098de.png)

**Comment by marvingreenberg** [comment]
You didn't say - are you using the latest (2.1.0) version of the plugin?

**Comment by marvingreenberg** [comment]
I've duplicated the failure.  I have a fix for the first part (layout of lower) but not the second part - writing the SVG.  Sketchup is a pain - that face has 1485 edge segments, which makes debugging this difficult.  SU under undefined situations can collapse small edges and cause vertices to be deleted.  I'll look at this more later.

As an aside, those notches will be a problem since they're only 1/8" so the SO won't let the bit follow the edge (but I guess you can fo the offset thing)

**Comment by ropandsaw** [comment]
Hey Marvin, 

Thanks for your work and efforts to create a smooth running plugin for creating SVG files- I was really thankful when I came across the plugin. 

I downloaded it yesterday for the first time, and have been using version 2.1.0 

You're correct about the notches, I may need to resize them, but I think I'll try it first with an offset path. I went ahead and created an svg file with the systainer insert models via Adobe Illustrator- not too bad, but definitely not as nice as your plug in. I mostly wanted to pass on the information on to you for debugging if you thought it necessary- I hear what you're saying with the all the edge segments, it may just be part of the beast. Anyway, thanks again for you work in developing the plug in- as near a luddite as one can be anymore, I appreciate your work!

Bryce

**Comment by ropandsaw** [comment]
Marvin,

This is not directly related to your plugin, but the model I was using in sketchup...

After following the workflow of of sketchup-illustrator-.svg I ended up with a file, got it on my shaper and placed it in workspace and got ready to cut. To my dismay, the paths were not complete on the model, so I could not have a complete cutting path. I went back to illustrator to connect all paths, and surprise surprise illustrator couldn't connect the paths, saying:

![screen shot 2018-03-10 at 10 53 23 am](https://user-images.githubusercontent.com/37227762/37245156-4d2f9d40-2451-11e8-991c-07c5a032a33d.png)

so...maybe I just need to bite the bullet and draw my own model.

**Comment by marvingreenberg** [comment]
Almost fixed.  Regardless that Illustrator has some issue, as far as SU is concerned it is a face so has a continuous path.  But SU behaves weirdly drawing small arcs -- those 1/8" slots -- and so some of the edges get deleted when copying which breaks my code. Illustrator or the DXF export is having some different problem probably.  I've attached the almost-correct SVG as a zip file, I'll try to finish fixing this... sometime.

[systainer_svg.zip](https://github.com/marvingreenberg/FaceSVG/files/1805317/systainer_svg.zip)

![systainer](https://user-images.githubusercontent.com/216707/37320259-4415a7d2-2649-11e8-88ed-6f8ba12d82eb.png)

**Comment by marvingreenberg** [comment]
A refactoring of how the faces are copied a2de9560175cab1d3774f6e54441f9c0b929064c addresses this issue.  This is available in [release 2.2.0](https://github.com/marvingreenberg/FaceSVG/releases/tag/2.2.0)
